### ISSUE TITLE
Password grant token gets rejected

### ISSUE THREAD

**Issue by mikemilano** [trikoder/oauth2-bundle#106]
I've created a client with `grants` set to `client_credentials password`.

I can get a tokens issued with either grant type but requests made with tokens issued via password are rejected.

> The resource server rejected the request.

Both tokens look similar in the `oauth2_access_token` table except the one created via password has a `user_identifier` that represents the user.

![Screen Shot 2019-09-24 at 8 18 08 PM](https://user-images.githubusercontent.com/1287855/65566692-807e3d00-df08-11e9-959d-8556b1bbf9b6.png)

What would cause the password generated token to be rejected, or how can I troubleshoot it?

There's nothing to my controller that I'm getting 2 different results with:
```
class ExampleController extends AbstractController
{
    /**
     * @Route("/api/example", name="example")
     */
    public function index()
    {
        return $this->json(['status' => 1]);
        ...
```

**Comment by thePhrenologist** [comment]
did you implement a UserResolveListener: https://github.com/trikoder/oauth2-bundle/blob/v2.x/docs/password-grant-handling.md ?

did you set ````enable_password_grant: true```` in config/packages/trikoder_oauth2.yaml?

**Comment by mikemilano** [comment]
@thePhrenologist yes to both. I think the email address in the `oauth2_access_token` record proves that part is configured and working properly.

**Comment by mikemilano** [comment]
security.yaml
```yaml
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        ...
        api_token:
            pattern: ^/token$
            security: false
        api:
            pattern: ^/api
            security: true
            stateless: true
            oauth2: true
```

services.yaml
```yaml
    App\EventListener\UserResolveListener:
        tags:
            - { name: kernel.event_listener, event: trikoder.oauth2.user_resolve, method: onUserResolve }
```

UserResolveListener.php
```php
<?php

namespace App\EventListener;

use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Trikoder\Bundle\OAuth2Bundle\Event\UserResolveEvent;

final class UserResolveListener
{
    /**
     * @var UserProviderInterface
     */
    private $userProvider;

    /**
     * @var UserPasswordEncoderInterface
     */
    private $passwordEncoder;

    /**
     * UserResolveListener constructor.
     * @param UserProviderInterface $userProvider
     * @param UserPasswordEncoderInterface $passwordEncoder
     */
    public function __construct(UserProviderInterface $userProvider, UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->userProvider = $userProvider;
        $this->passwordEncoder = $passwordEncoder;
    }

    /**
     * @param UserResolveEvent $event
     */
    public function onUserResolve(UserResolveEvent $event): void
    {
        $user = $this->userProvider->loadUserByUsername($event->getUsername());

        if (null === $user) {
            return;
        }

        if (!$this->passwordEncoder->isPasswordValid($user, $event->getPassword())) {
            return;
        }

        $event->setUser($user);
    }
}
```

trikoder_oauth2.yaml
```yaml
trikoder_oauth2:
  authorization_server: # Required
    # Full path to the private key file.
    # How to generate a private key: https://oauth2.thephpleague.com/installation/#generating-public-and-private-keys
    private_key: '%kernel.project_dir%/var/oauth/private.key'

    # Passphrase of the private key, if any
    private_key_passphrase: null

    # The plain string or the ascii safe string used to create a Defuse\Crypto\Key to be used as an encryption key.
    # How to generate an encryption key: https://oauth2.thephpleague.com/installation/#string-password
    encryption_key: '%env(resolve:OAUTH2_ENCRYPTION_KEY)%'

    # The type of value of 'encryption_key'
    encryption_key_type:  plain # One of "plain"; "defuse"

    # How long the issued access token should be valid for.
    # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
    access_token_ttl: PT1H

    # How long the issued refresh token should be valid for.
    # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
    refresh_token_ttl: P1M

    # How long the issued auth code should be valid for.
    # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
    auth_code_ttl: PT10M

    # Whether to enable the client credentials grant
    enable_client_credentials_grant: true

    # Whether to enable the password grant
    enable_password_grant: true

    # Whether to enable the refresh token grant
    enable_refresh_token_grant: true

    # Whether to enable the authorization code grant
    enable_auth_code_grant: true

    # Whether to enable the implicit grant
    enable_implicit_grant: true
  resource_server: # Required
    # Full path to the public key file
    # How to generate a public key: https://oauth2.thephpleague.com/installation/#generating-public-and-private-keys
    public_key: '%kernel.project_dir%/var/oauth/public.key'

  # Scopes that you wish to utilize in your application.
  # This should be a simple array of strings.
  scopes: [full]

  # Configures different persistence methods that can be used by the bundle for saving client and token data.
  # Only one persistence method can be configured at a time.
  persistence: # Required
    doctrine:
      # Name of the entity manager that you wish to use for managing clients and tokens.
      entity_manager: default
    #in_memory: ~

  # The priority of the event listener that converts an Exception to a Response
  exception_event_listener_priority: 10
```
