### ISSUE TITLE
HTTP 500: The current token must be set to use the "security" attribute (is the URL behind a firewall?).

### ISSUE THREAD

**Issue by cnizzardini** [trikoder/oauth2-bundle#155]
We have previously used JWT tokens backed by a MongoDb provider on API Platform. Now we are implementing OAuth2 using this bundle. We can get a bearer token using a `password` grant, however, when performing an HTTP POST against an endpoint known to work we get this error:

> The current token must be set to use the "security" attribute (is the URL behind a firewall?).

```yaml
#security.yaml
security:
    encoders:
        App\Document\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        mongo_provider:
            mongodb:
                class: App\Document\User
                property: email
                    
    firewalls:
        main:
            pattern: ^/$
            security: true
            stateless: true
            oauth2: true
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        #main:
        #    stateless: true
        #    anonymous: true
        #    provider: mongo_provider
        #    oauth2: true
        #    json_login:
        #        check_path: /authentication_token
        #        username_path: email
        #        password_path: password
        #        success_handler: lexik_jwt_authentication.handler.authentication_success
        #        failure_handler: lexik_jwt_authentication.handler.authentication_failure
        #    guard:
        #        authenticators:
        #            - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```

My hunch is we may need to move the roles into the OAuth2 client scopes, but I am not sure if that is the right approach. Here is the Document which defines roles, resources etc... that is read by the Api Platform bundle.

```php
<?php

namespace App\Document;

#... removed use statements for brevity

/**
 * @ODM\Document
 * @ApiResource(
 *     collectionOperations={
 *         "get",
 *         "post"={"security_post_denormalize"="is_granted(['ROLE_STANDARD', 'ROLE_PREMIUM', 'ROLE_ADMIN'])"},
 *     },
 *   itemOperations={
 *         "get"={"security_post_denormalize"="is_granted(['ROLE_STANARD','ROLE_PREMIUM','ROLE_ADMIN'])"},
 *         "put"={"security_post_denormalize"="is_granted(['ROLE_STANDARD','ROLE_PREMIUM','ROLE_ADMIN'])"},
 *         "patch"={"security_post_denormalize"="is_granted(['ROLE_STANDARD','ROLE_PREMIUM','ROLE_ADMIN'])"},
 *         "delete"={"security_post_denormalize"="is_granted(['ROLE_STANDARD','ROLE_PREMIUM','ROLE_ADMIN'])"}
 *     },
 *     normalizationContext={"groups"={"portfolio:read","admin"}},
 *     denormalizationContext={"groups"={"portfolio:write","admin"}},
 * )
 */
class Portfolio
```
