### ISSUE TITLE
adding prefix to /token route - ingress && k8s

### ISSUE THREAD

**Issue by gustvao** [trikoder/oauth2-bundle#206]
Guys, how do I add a prefix to the token and authenticate routes?

The thing is that I am using k8s with an Ingress that makes all my backend requests com from domain.com/api/*.

If I cannot make /token come as /api/token, I will never be able to reach token route in prod because domain.com/token belongs to another pod (application), does it make sense?

pls any guidance will be much appreciated

**Comment by X-Coder264** [comment]
You import our routes (as per our readme.md):

```yml
oauth2:
    resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'
```

You just need to add the prefix here so it'd be:

```yml
oauth2:
    resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'
    prefix: '/api'
```
