### ISSUE TITLE
A Token was not found in the TokenStorage

### ISSUE THREAD

**Issue by uxen-kv** [trikoder/oauth2-bundle#28]
Hello,

I am trying to implement your library in a project, an I'm unable to get it working.
I can get an access token by going to a /token url, but after, when passing this token to my API's routes, I get a 401 unauthorized response.

When going to the symfony profiler, I can see that a AuthenticationCredentialsNotFoundException is thrown.

Here is my configuration :

 - Symfony 4.2.3
 - php 7.2.15

security.yaml : 

```yaml
security:
    providers:
        app_user_provider:
            entity:
                class: Trikoder\Bundle\OAuth2Bundle\Security\Authentication\Provider\OAuth2Provider
    firewalls:
        api_token:
            pattern: ^/api/token$
            security: false
        api:
            pattern: ^/api
            security: true
            stateless: true
            oauth2: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
```

trikoder_oauth2.yaml : 

```yaml
trikoder_oauth2:

    authorization_server:

        # Full path to the private key file.
        # How to generate a private key: https://oauth2.thephpleague.com/installation/#generating-public-and-private-keys
        private_key: "%kernel.root_dir%/../var/oauth/private.key"

        # The string used as an encryption key.
        # How to generate an encryption key: https://oauth2.thephpleague.com/installation/#string-password
        encryption_key: "generated as phpleague doc says"

        # How long the issued access token should be valid for.
        # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
        access_token_ttl: PT1H

        # How long the issued refresh token should be valid for.
        # The value should be a valid interval: http://php.net/manual/en/dateinterval.construct.php#refsect1-dateinterval.construct-parameters
        refresh_token_ttl: P1M

    resource_server:

        # Full path to the public key file
        # How to generate a public key: https://oauth2.thephpleague.com/installation/#generating-public-and-private-keys
        public_key: "%kernel.root_dir%/../var/oauth/public.key"

    # Scopes that you wish to utilize in your application.
    # This should be a simple array of strings.
    scopes: []

    # Configures different persistence methods that can be used by the bundle for saving client and token data.
    # Only one persistence method can be configured at a time.
    persistence:

        doctrine:

            # Name of the entity manager that you wish to use for managing clients and tokens.
            entity_manager: default # Required

        #in_memory: ~
```

I made a chmod -R a+rwx on my var/oauth folder.

Am I missing something ?

Thanks in advance

**Comment by spideyfusion** [comment]
You are not suppose to define a user provider on your own. Remove the following configuration block:

```yaml
providers:
    app_user_provider:
        entity:
            class: Trikoder\Bundle\OAuth2Bundle\Security\Authentication\Provider\OAuth2Provider
```

If you have users in your application and want to handle requests on their behalf, consult the documentation on how to implement `password` grant type handling:

https://github.com/trikoder/oauth2-bundle/blob/master/docs/password-grant-handling.md
