### ISSUE TITLE
The authorization grant type is not supported by the authorization server

### ISSUE THREAD

**Issue by thePhrenologist** [trikoder/oauth2-bundle#69]
Hi, thanks for this bundle.

I try to use it with symfony 4.2

composer.json:

````
  "trikoder/oauth2-bundle": "dev-master",
  "symfony/psr-http-message-bridge": "^1.2",
  "nyholm/psr7": "^1.1",
  "sensio/framework-extra-bundle": "^5.1",
````

security.yml
````
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_token:
            pattern: ^/token$
            security: false

        oauth_authorize: # here we handle the GRANT_TYPE_AUTH_CODE
            pattern: ^/authorize
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            anonymous: true
            logout:
                path:                       fos_user_security_logout
                target:                     fos_user_security_login

        api: # the resource server: should be protected
            pattern: ^/api
            security: true
            stateless: true
            oauth2: true
            provider: fos_userbundle
            anonymous:  false # can be omitted as its default value

    access_control:
        - { path: ^/authorize, roles: IS_AUTHENTICATED_REMEMBERED }
````

Bundle is enabled, I can access the routes and run the commands.

My issue: I cannot get a token:

````
POST http://127.0.0.1:8000/token?client_id=de7a2a311699b6636566610ebfc01449&client_secret=94a8555796d6d78e1a050c9b3bbca4dc0f0d9d2e172b9e87a391b90f76e965a8d818314175ea7136d266fac07d2720fc401420df8b0c5f3e05b1711c39c154b9&grant_type=client_credentials&scope=read 
````

gives:

````
{
    "error": "unsupported_grant_type",
    "error_description": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check that all required parameters have been provided",
    "message": "The authorization grant type is not supported by the authorization server."
}
````
