### ISSUE TITLE
Need help with authorization grant flow

### ISSUE THREAD

**Issue by thePhrenologist** [trikoder/oauth2-bundle#70]
Hi guys,

I try to set up this bundle with SF4.2 and FOS Userbundle. I have the password flow and the client credentials flow working, But somehow I cannot get the authorization code grant working. I'm testing it using Postman. Do you guys have a demo application, or can you review these snippets? thanks a lot

composer.json
````
 "trikoder/oauth2-bundle": "dev-master"
````

For the password flow I implemented the UserResolveListener
````
App\EventListener\UserResolveListener:
        arguments:
            - '@fos_user.user_provider.username'
            - '@security.password_encoder'
        tags:
            - { name: kernel.event_listener, event: trikoder.oauth2.user_resolve, method: onUserResolve }

```` 
routes.yml
````
oauth2:
  resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'
  prefix: /oauth/v2
````

trikoder_oauth2.yml: I added enable_refresh_token_grant: true, Is that valid?
````
trikoder_oauth2:

  authorization_server:
    private_key: '%kernel.project_dir%/var/private.key'
    encryption_key: '+Ht5kEwG2bAlCKSs13LPu51BCyu+643PKBRdnCc1JWY='
    access_token_ttl: PT1H
    refresh_token_ttl: P1M
    enable_client_credentials_grant: true
    enable_password_grant: true
    enable_refresh_token_grant: true # I added this myself. Is this valid?
    enable_auth_code_grant: true
    auth_code_ttl: PT10M

  resource_server:
    public_key: '%kernel.project_dir%/var/public.key'

  scopes: ['read']

  persistence:
    doctrine:
      entity_manager: default # Required

  exception_event_listener_priority: 10
````

Curl request ( I use Postman)
````
curl -X POST \
  http://127.0.0.1:8000/oauth/v2/authorize \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Host: 127.0.0.1:8000' \
  -H 'Postman-Token: 8e0360e7-dbf6-48be-b090-08d2cc89d7df,724f973b-44cc-43c6-b799-a394b6017e2c' \
  -H 'User-Agent: PostmanRuntime/7.15.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 663' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -H 'cookie: PHPSESSID=tk5c6pb1evmsjskg2n8rdstd58' \
  -b PHPSESSID=tk5c6pb1evmsjskg2n8rdstd58 \
  -F response_type=code \
  -F client_id=de7a2a311699b6636566610ebfc01449 \
  -F redirect_uri=http://127.0.0.1:4200 \
  -F state=lololol \
  -F scope=read
````

Response
````
{
    "error": "unsupported_grant_type",
    "error_description": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check that all required parameters have been provided",
    "message": "The authorization grant type is not supported by the authorization server."
}
````
