### ISSUE TITLE
Authorize always go to login form

### ISSUE THREAD

**Issue by bbarhoum** [trikoder/oauth2-bundle#81]
Hi, I need help please.
I'm trying to implement Authorization grant flow. 
Everything is working for me.
The problem is that when accessing the authorize uri, i'm redirected to login page even if I'm already logedin.
```
security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            security: true
            stateless: true
            oauth2: true
        main:
            pattern: ^/
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\FormLoginAuthenticator
            logout:
                path: main_logout

    access_control:
        - { path: ^/authorize, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
```
Thanks

**Comment by Nyholm** [comment]
What do you mean when you say "authorize uri"? Is that the `Trikoder\Bundle\OAuth2Bundle\Controller\AuthorizationController::indexAction`? 
Why are you accessing it multiple times? Or do you get redirected there?

Is that URL behind your "api" firewall? If so, you get redirected to login because it is stateless.

**Comment by bbarhoum** [comment]
It's the Trikoder\Bundle\OAuth2Bundle\Controller\AuthorizationController::indexAction and the route is /authorize. In the access_control i have: - { path: ^/authorize, roles: IS_AUTHENTICATED_REMEMBERED }

I get redirected to the login page every time when I try to make authorization call.

**Comment by Nyholm** [comment]
That is because you are using stateless config: 
```yaml
        api:
            pattern: ^/api
            security: true
            stateless: true  # This line
```

Stateless means that we dont hold any state about previous logins. We must authorise every time. This is used when an API client makes requests. Every request must include an Authorization header.
