### ISSUE TITLE
Passive authentication

### ISSUE THREAD

**Issue by maximerenou** [trikoder/oauth2-bundle#93]
I would like to create a route that is public, but still be able to use `$this->getUser()` which could returns `User` or `null` depending on _if your security system detects a valid OAuth token or not_. Does your bundle can be used that way ? This is the default behavior of the classic authentication system.

**Comment by maximerenou** [comment]
OK found it.

Just add `anonymous: true` in your `security.yaml` :

```
         api:
             pattern: ^/api
             security: true
             anonymous: true
             stateless: true
             oauth2: true
```

btw, good job guys!
